######################################################################
#
# File name : sim_tb_top_compile.do
# Created on: Sat Aug 07 14:20:12 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib "+incdir+../../src" \
"../../src/clocking/mig_7series_v4_2_clk_ibuf.v" \
"../../src/clocking/mig_7series_v4_2_infrastructure.v" \
"../../src/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
"../../src/clocking/mig_7series_v4_2_tempmon.v" \
"../../src/controller/mig_7series_v4_2_arb_mux.v" \
"../../src/controller/mig_7series_v4_2_arb_row_col.v" \
"../../src/controller/mig_7series_v4_2_arb_select.v" \
"../../src/controller/mig_7series_v4_2_bank_cntrl.v" \
"../../src/controller/mig_7series_v4_2_bank_common.v" \
"../../src/controller/mig_7series_v4_2_bank_compare.v" \
"../../src/controller/mig_7series_v4_2_bank_mach.v" \
"../../src/controller/mig_7series_v4_2_bank_queue.v" \
"../../src/controller/mig_7series_v4_2_bank_state.v" \
"../../src/controller/mig_7series_v4_2_col_mach.v" \
"../../src/controller/mig_7series_v4_2_mc.v" \
"../../src/controller/mig_7series_v4_2_rank_cntrl.v" \
"../../src/controller/mig_7series_v4_2_rank_common.v" \
"../../src/controller/mig_7series_v4_2_rank_mach.v" \
"../../src/controller/mig_7series_v4_2_round_robin_arb.v" \
"../../src/ecc/mig_7series_v4_2_ecc_buf.v" \
"../../src/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
"../../src/ecc/mig_7series_v4_2_ecc_gen.v" \
"../../src/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
"../../src/ecc/mig_7series_v4_2_fi_xor.v" \
"../../src/ip_top/mig_7series_v4_2_memc_ui_top_std.v" \
"../../src/ip_top/mig_7series_v4_2_mem_intfc.v" \
"../../src/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
"../../src/phy/mig_7series_v4_2_ddr_byte_lane.v" \
"../../src/phy/mig_7series_v4_2_ddr_calib_top.v" \
"../../src/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
"../../src/phy/mig_7series_v4_2_ddr_mc_phy.v" \
"../../src/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
"../../src/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_init.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_top.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
"../../src/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
"../../src/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
"../../src/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
"../../src/phy/mig_7series_v4_2_poc_cc.v" \
"../../src/phy/mig_7series_v4_2_poc_edge_store.v" \
"../../src/phy/mig_7series_v4_2_poc_meta.v" \
"../../src/phy/mig_7series_v4_2_poc_pd.v" \
"../../src/phy/mig_7series_v4_2_poc_tap_base.v" \
"../../src/phy/mig_7series_v4_2_poc_top.v" \
"../../src/ui/mig_7series_v4_2_ui_cmd.v" \
"../../src/ui/mig_7series_v4_2_ui_rd_data.v" \
"../../src/ui/mig_7series_v4_2_ui_top.v" \
"../../src/ui/mig_7series_v4_2_ui_wr_data.v" \
"../../src/ddr3_mig_sim.v" \
"../../src/ddr3.v" \
"../../src/ddr3_top.v" \

C:\\modeltech64_10.5\\win64\\vlog -64 -incr -sv -work xil_defaultlib "+incdir+../../src" \
"../tb_src/model/ddr3_model.sv" \

C:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib "+incdir+../../src" \
"../tb_src/ddr3_top_tb.v" \

# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

# quit -force

